### ISSUE TITLE
port forward not work

### ISSUE THREAD

**Issue by Zo0oX** [ambader/ipv4-ipv6#1]
hello

i do this for v2ray portforwarding but not work, how can i fix this ?

thanks

**Comment by ambader** [comment]
You want to apply a framework I don't know. What I described is how you have to configure a server to use socat to connect ipv4 to ipv6. Have you even installed socat ? As you don't provide any information to describe the issue, i highly recommend to give up.

**Comment by Zo0oX** [comment]
> You want to apply a framework I don't know. What I described is how you have to configure a server to use socat to connect ipv4 to ipv6. Have you even installed socat ? As you don't provide any information to describe the issue, i highly recommend to give up.

yes i apply framework
and i install socat

i use socat fot portforward, but dome servers speed is very low in some days

**Comment by ambader** [comment]
So it works, but the speed is low. What are you expecting ?

**Comment by Zo0oX** [comment]
no, my way is work, your code not working my friend, but my way is not complete code.
